//
//  Configuration.m
//  SwaggerPetstore
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#import "Configuration.h"

/** The base Uri for API calls */
NSString* Configuration_BaseUri = @"http://petstore.swagger.io/v2";

/** The OAuth 2.0 access token to be set before API calls */
/** Replace the value of OAuthAccessToken with an appropriate value */
NSString* Configuration_OAuthAccessToken = @"TODO: Replace";

