//
//  Configuration.h
//  SwaggerPetstore
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef SwaggerPetstore_Configuration_h
#define SwaggerPetstore_Configuration_h

/** The base Uri for API calls */
extern NSString* Configuration_BaseUri;

/** The OAuth 2.0 access token to be set before API calls */
/** extern reference to the config variable OAuthAccessToken */
extern NSString* Configuration_OAuthAccessToken;

#endif
