//
//  ApiResponse.h
//  SwaggerPetstore
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_APIRESPONSE
#define APIMATIC_APIRESPONSE

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol ApiResponse
@end

@interface ApiResponse : JSONModel

/**
* TODO: Write general description for this field
*/
@property NSNumber* code;

/**
* TODO: Write general description for this field
*/
@property NSString* type;

/**
* TODO: Write general description for this field
*/
@property NSString* message;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif