//
//  ApiResponse.m
//  SwaggerPetstore
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#import "ApiResponse.h"

@implementation ApiResponse

/**
* TODO: Write general description for this method
*/
@synthesize code;

/**
* TODO: Write general description for this method
*/
@synthesize type;

/**
* TODO: Write general description for this method
*/
@synthesize message;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"code": @"code",
        @"type": @"type",
        @"message": @"message"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end