//
//  Order.h
//  SwaggerPetstore
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_ORDER
#define APIMATIC_ORDER

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "StatusEnum.h"
#import "StatusEnumHelper.h"


//protocol defined for deserialization of JSON
@protocol Order
@end

@interface Order : JSONModel

/**
* TODO: Write general description for this field
*/
@property NSNumber* mid;

/**
* TODO: Write general description for this field
*/
@property NSNumber* petId;

/**
* TODO: Write general description for this field
*/
@property NSNumber* quantity;

/**
* TODO: Write general description for this field
*/
@property NSDate* shipDate;

/**
* Order Status
*/
@property enum StatusEnum status;

/**
* TODO: Write general description for this field
*/
@property BOOL complete;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif