//
//  Pet.h
//  SwaggerPetstore
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_PET
#define APIMATIC_PET

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "Category.h"
#import "Tag.h"
#import "Status6Enum.h"
#import "Status6EnumHelper.h"


//protocol defined for deserialization of JSON
@protocol Pet
@end

@interface Pet : JSONModel

/**
* TODO: Write general description for this field
*/
@property NSString* name;

/**
* TODO: Write general description for this field
*/
@property NSArray* photoUrls;

/**
* TODO: Write general description for this field
*/
@property NSNumber* mid;

/**
* TODO: Write general description for this field
*/
@property Category* mcategory;

/**
* TODO: Write general description for this field
*/
@property NSArray<Tag> * tags;

/**
* pet status in the store
*/
@property enum Status6Enum status;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif