//
//  StatusEnum.h
//  SwaggerPetstore
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_STATUSENUM
#define APIMATIC_STATUSENUM
 
enum StatusEnum
{
        StatusPlaced, //TODO: Write general description for this method
        StatusApproved, //TODO: Write general description for this method
        StatusDelivered, //TODO: Write general description for this method
};

#endif