//
//  Status6Enum.h
//  SwaggerPetstore
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_STATUS6ENUMHELPER
#define APIMATIC_STATUS6ENUMHELPER

#include "Status6Enum.h"

/**
* Helper class interface for Status6Enum to NSString conversion
*/
@interface Status6EnumHelper : NSObject

+(id) stringFromStatus6Enum:(enum Status6Enum) status6Enum withDefault: (id) defaultValue;

+(NSArray<NSString*>*) stringArrayFromStatus6EnumArray:(NSArray<NSNumber*>*) array;


+(enum Status6Enum) status6EnumFromString:(NSString*) strValue;

+(NSArray<NSNumber*>*) status6EnumArrayFromStringArray:(NSArray<NSString*>*) array;

@end

#endif