//
//  Status6Enum.h
//  SwaggerPetstore
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_STATUS6ENUM
#define APIMATIC_STATUS6ENUM
 
enum Status6Enum
{
        Status6Available, //TODO: Write general description for this method
        Status6Pending, //TODO: Write general description for this method
        Status6Sold, //TODO: Write general description for this method
};

#endif