//
//  Status6Enum.h
//  SwaggerPetstore
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#include "Status6EnumHelper.h"

/**
* Helper class implementation for Status6Enum to NSString conversion
*/
@implementation Status6EnumHelper

+(id) stringFromStatus6Enum:(enum Status6Enum) status6Enum withDefault: (id) defaultValue
{
    switch(status6Enum)
    {
        case Status6Available:
            return @"available";

        case Status6Pending:
            return @"pending";

        case Status6Sold:
            return @"sold";

        default:
            return defaultValue;
    }
}

+(NSArray<NSString*>*) stringArrayFromStatus6EnumArray:(NSArray<NSNumber*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSNumber* numberValue in array){
        NSNumber* stringValue = [Status6EnumHelper stringFromStatus6Enum:(enum Status6Enum) numberValue.intValue withDefault:[NSNull null]];
        [enums addObject:stringValue];
    }
    return [enums copy];
}

+(enum Status6Enum) status6EnumFromString:(NSString*) strValue
{
    NSArray* Status6EnumArray = [NSArray arrayWithObjects:
                                        @"available",
                                        @"pending",
                                        @"sold",
                                        nil];

    return (enum Status6Enum) [Status6EnumArray indexOfObject: strValue];
}


+(NSArray<NSNumber*>*) status6EnumArrayFromStringArray:(NSArray<NSString*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSString* enumValue in array){
        NSNumber* numberValue = [NSNumber numberWithInt:[ Status6EnumHelper status6EnumFromString:enumValue]];
        [enums addObject:numberValue];
    }
    return [enums copy];
}

@end